name: Ecocraft
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^1.2.1
  tflite_flutter: ^0.12.1
  image: ^4.8.0
  http: ^1.2.0
  path_provider: ^2.1.2
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/offline_crafts.json
    - assets/final_waste_detector_float32.tflite
    - assets/labels.txt